// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zaovvyeetigozeeoydqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inphb3Z2eWVldGlnb3plZW95ZHF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MDY2MjYsImV4cCI6MjA3MjQ4MjYyNn0.7cXN0RRCu05e72ML5jujVvks8DOsXmkvncPI42V_oE8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});